### ISSUE TITLE
[Feature Request] Better Discord Plugin Version

### ISSUE THREAD

**Issue by DeathKhan** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#3]
Given the desktop app is essentially a chromium instance, couldn't this be turned into a better discord plug in??

**Comment by edisionnano** [comment]
Discord clients dont do screenshare via js like browsers do so it can't be done as a bd plugin since these are only js. Getting screenshare with audio on a client is technically possible tho but probably not worth it. We would either need to reverse engineer and perhaps reimplement mediaengine or find how all these streams are fed into webrtc and hijack them. There does exist one linux discord client that can capture system audio but its the android one so I dont know whether this helps or not.

**Comment by ChrisJAllan** [comment]
Is there any way to convince the app version it's running in a browser? Or would that negate the benefits of using the app in the first place (encoding speed, fps, resolution, etc).

**Comment by JustCryen** [comment]
Good thing I checked closed issues before asking for exactly the same thing…
That sucks…
I've been trying to get this working under electron for the past week but… I've never used JS previously so no surprises I haven't been able to do anything.

**Comment by edisionnano** [comment]
> Good thing I checked closed issues before asking for exactly the same thing… That sucks… I've been trying to get this working under electron for the past week but… I've never used JS previously so no surprises I haven't been able to do anything.

You probably wont get very far. Unless you ship your own custom electron with getusermedia support and rewrite discords js code to utilize it instead of using their closed source native library. So basically you'd have to reimplement all of their client js code. By that I mean the js files discord loads from the internet not the ones bundled with the client. If you are going this far you may as well create a native Discord client.

**Comment by ChrisJAllan** [comment]
> You probably wont get very far. Unless you ship your own custom electron with getusermedia support and rewrite discords js code to utilize it instead of using their closed source native library. So basically you'd have to reimplement all of their client js code. By that I mean the js files discord loads from the internet not the ones bundled with the client. If you are going this far you may as well create a native Discord client.

Overwriting `getusermedia` is the easy part, that's how the browser hacks work. The problem is that the app doesn't use `getusermedia` at all, it uses it's own native library. If we work out the api for that, it might be possible to `LD_PRELOAD` a replacement

**Comment by edisionnano** [comment]
> > You probably wont get very far. Unless you ship your own custom electron with getusermedia support and rewrite discords js code to utilize it instead of using their closed source native library. So basically you'd have to reimplement all of their client js code. By that I mean the js files discord loads from the internet not the ones bundled with the client. If you are going this far you may as well create a native Discord client.
> 
> Overwriting `getusermedia` is the easy part, that's how the browser hacks work. The problem is that the app doesn't use `getusermedia` at all, it uses it's own native library. If we work out the api for that, it might be possible to `LD_PRELOAD` a replacement

Yes that's what I said, its absolutely of no use redefining getusermedia if Discord doesn't call it in the first place. Since the client uses FFMPEG we could declare soundshare as supported on Linux in the voice module and provide a patched FFMPEG that captures audio and hope this works. We'd have to find out how Discord does screensharing; if it actually uses ffmpeg and which function. And if thats the case fork ffmpeg and patcb the function to capture a microphone.
